/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "opencv2/opencv.hpp"
#include <string>
#include <vector>
#include <ctime>
#include <ctype.h>
#include <android/log.h>
#include <iostream>
#include <fstream>

#include <stdio.h>
#include <stdlib.h>

using namespace std;
using namespace cv;

#ifndef _Included_com_unicamp_alantavares_monocularopencv300_OpencvNativeClass
#define _Included_com_unicamp_alantavares_monocularopencv300_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif

void featureDetection(Mat& imgGray1, vector<Point2f>& points1);

void featureTracking(Mat& imgGray1, Mat& imgGray2, vector<Point2f>& points1, vector<Point2f>& points2, vector<uchar>& status);

JNIEXPORT void JNICALL Java_com_unicamp_alantavares_monocularopencv300_OpencvNativeClass_FindFeatures
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
